[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
"solmate/=lib/solmate/src/",
"chainlink/=lib/chainlink/"
]
ffi = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config